apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operatorframework.io/cluster-monitoring: "true"
    operatorframework.io/suggested-namespace: windows-machine-config-operator
    repository: https://github.com/openshift/windows-machine-config-operator
  name: windows-machine-config-operator.v0.0.0
  namespace: windows-machine-config-operator
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Placeholder description
  displayName: Windows Machine Config Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - events
          - nodes
          verbs:
          - '*'
        - apiGroups:
          - config.openshift.io
          resources:
          - infrastructures
          - networks
          verbs:
          - get
        - apiGroups:
          - certificates.k8s.io
          resources:
          - certificatesigningrequests
          - certificatesigningrequests/approval
          verbs:
          - get
          - list
          - update
        - apiGroups:
          - operator.openshift.io
          resources:
          - networks
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
          - list
        - apiGroups:
          - certificates.k8s.io
          resources:
          - signers
          verbs:
          - approve
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - get
        - apiGroups:
          - machine.openshift.io
          resources:
          - machines
          verbs:
          - get
          - list
          - watch
        serviceAccountName: windows-machine-config-operator
      deployments:
      - name: windows-machine-config-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: windows-machine-config-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: windows-machine-config-operator
            spec:
              containers:
              - args:
                - --zap-level=debug
                - --zap-encoder=console
                command:
                - windows-machine-config-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: windows-machine-config-operator
                image: REPLACE_IMAGE
                imagePullPolicy: Always
                name: windows-machine-config-operator
                resources: {}
                volumeMounts:
                - mountPath: /etc/private-key/
                  name: cloud-private-key
                  readOnly: true
              hostNetwork: true
              serviceAccountName: windows-machine-config-operator
              volumes:
              - name: cloud-private-key
                secret:
                  secretName: cloud-private-key
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - delete
          - get
        - apiGroups:
          - ""
          resources:
          - services
          - services/finalizers
          verbs:
          - create
          - delete
          - get
          - update
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - create
          - get
          - update
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - windows-machine-config-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - hostnetwork
          resources:
          - securitycontextconstraints
          verbs:
          - use
        serviceAccountName: windows-machine-config-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - windows
  maintainers:
  - {}
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.0
